//creates users

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "AgabaTest3",
  "lastName": "Agnes",
  "email": "kafkatest3@gmail.com",
  "tel": "0772365100",
  "district": "Mukono",
  "userCreatedAt": "",
  "username": ""
}
###